# fly.toml file generated for compralo on 2023-04-11T14:34:17-05:00

app = "compralo"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bog"
processes = []
web = "bin/rails fly:server"
worker = "bundle exec sidekiq"

[deploy]
  release_command = "bin/rails db:prepare"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
